#+Title: Unidad 01 - Introducción y Virtualización
#+Author: Angel Berlanas Vicente

#+LATEX_HEADER: \hypersetup{colorlinks=true,urlcolor=blue}

#+LATEX_HEADER: \usepackage{fancyhdr}
#+LATEX_HEADER: \fancyhead{} % clear all header fields
#+LATEX_HEADER: \pagestyle{fancy}
#+LATEX_HEADER: \fancyhead[R]{2-SMX: SOX}
#+LATEX_HEADER: \fancyhead[L]{Infraestructura]}
#+LATEX_HEADER: \usepackage{wallpaper}
#+LATEX_HEADER: \ULCornerWallPaper{0.9}{../rsrc/logos/header_europa.png}
#+LATEX_HEADER: \CenterWallPaper{0.7}{../rsrc/logos/watermark_1.png}

\newpage
* Infraestructura Inicial

Vamos a comenzar repasando los conceptos que vimos a lo largo del año pasado de configuración
e instalación de máquinas virtuales.

Para la realización de las prácticas de este módulo, y del módulo de SER (/Servicios en Red/),
utilizaremos 4 Máquinas Virtuales (cómo /mínimo/).

- Windows 10 - *Client*
- Windows 2019 - *Server*
- Xubuntu 20.04 - *Client*
- Ubuntu Server 20.04 - *Server*

A lo largo del curso estas máquinas irán comunicándose entre ellas, y las configuraremos en redes
diferentes, en estructuras diferentes, etc.

** Usuarios Administradores



Adjunto tabla resumen de las caracterísiticas de las máquinas.

#+ATTR_LaTeX: :align |r|c|c|c|c|
#+ATTR_LaTeX: :environment longtable 
| Máquina        | eths | Disco Duro | Usuario Admin | Password |
|----------------+------+------------+---------------+----------|
| Win10-Client   |    1 | 50GB       | winadmin      | Win4dmin |
| Windows-Server |    2 | 50GB       | winadmin      | Win4dmin |
| Xubuntu-Client |    1 | 10GB       | linadmin      | Lin4dmin |
| Ubuntu-Server  |    2 | 15GB       | linadmin      | Lin4dmin |


Todas las máquinas configurar con el parámetro de : =Usar Caché de E/S del Anfitrión=.

Por ahora, poner todas las máquinas con las tarjetas de red en *Adaptador Puente*, de tal 
manera que puedan ser accedidas desde cualquier ordenador de la red.

** Sobre la Instalación de Windows 10 

   Para la correcta configuración y puesta en marcha de Windows luego más adelante, 
   debéis utilizar la versión *Pro*, ya que será la que nos permitirá realizar las
   funciones de /Unión al dominio/, /creación de usuarios/, etc.

** Sobre la Instalación de Ubuntu Server

   Debido a que los Sistemas Operativos de Servidores suelen no tener disponible
   un acceso gráfico, a lo largo del curso vamos realizar todas las configuraciones
   sobre *Ubuntu Server* mediante la línea de comandos.

   Tareas como la ejecución de comandos, copiar y pegar desde internet, etc. Lo resolveremos
   mediante =SSH= u otras herramientas parecidas.

   Si para /estar más cómodos/ realizamos este tipo de acciones, no estamos siendo 
   especialmente /profesionales/.


\newpage


    #+BEGIN_SRC ditaa :file infraetructura.png

               +---------+       +---------+
               |         |       |         |
               | Windows |------>| Windows |
               | Server  |       |  10     |
               | 2019    |       |         | 
               +---------+       +---------+


              +---------+       +---------+
              |         |       |         |
              | Ubuntu  |------>| Xubuntu |
              | Server  |       |  20.04  |
              | 20.04   |       |         | 
              +---------+       +---------+


    #+END_SRC


