#+Title: Unidad 01 - Practica Miniping
#+Author: Angel Berlanas Vicente

#+LATEX_HEADER: \hypersetup{colorlinks=true,urlcolor=blue}

#+LATEX_HEADER: \usepackage{fancyhdr}
#+LATEX_HEADER: \fancyhead{} % clear all header fields
#+LATEX_HEADER: \pagestyle{fancy}
#+LATEX_HEADER: \fancyhead[R]{2-SMX:SOX - Practica}
#+LATEX_HEADER: \fancyhead[L]{UD01: Miniping]}

#+LATEX_HEADER:\usepackage{wallpaper}
#+LATEX_HEADER: \ULCornerWallPaper{0.9}{../rsrc/logos/header_europa.png}
#+LATEX_HEADER: \CenterWallPaper{0.7}{../rsrc/logos/watermark_1.png}

\newpage
* Tarea 01 : MiniPing.sh

Realizar un /script/ en Bash que utilizando variables (por ahora definidas en el propio 
fichero), compruebe mediante el comando ping (/por ejemplo/), si las máquinas instaladas
están accesibles.


#+BEGIN_SRC bash
#!/bin/bash

# Las Ips estan a modo de ejemplo.
LIN_SRV_IP="192.168.4.254"
LIN_CLIENT_IP="192.168.4.1"
WIN_SRV_IP="127.0.0.1"
WIN_CLIENT_IP="192.168.4.2"

# Comprobar para cada uno de ellos la conectividad, mostrando 
# un mensaje de error en caso de que no haya sido posible 
# realizar una conexion con el (ping).

#DO STUFF HERE

exit 0

#+END_SRC

Indicadle al profesor que habéis terminado para que pueda revisarlo.

Se valorará:

+ Qué funcione.
+ Qué esté documentado.
+ Qué la información esté presentada correctamente.
+ Posibles mejoras.


\newpage
* Tarea 02 : MiniPingPowerShell.ps1

  A continuación os presento un pequeño Script en =PowerShell= que realiza la /misma función/
  que el script presentado antes en =Bash=.

#+BEGIN_SRC PowerShell

# Esto es un Script realizado en PowerShell.

# La idea de este Script es que compruebe la conectividad con diferentes 
# maquinas. Lo Iremos ampliando a medida que lo necesitemos.

Write-Host " Welcome to the MiniPing.sh"

$LIN_SRV_IP="192.168.1.1"
$LIN_CLIENT_IP="192.168.1.2"
$WIN_SRV_IP="192.168.1.1"
$WIN_CLIENT_IP="192.168.1.12"

Write-Host " * Testing Connection with: $LIN_SRV_IP"

if ( (Test-NetConnection $LIN_SRV_IP).PingSucceeded){
    Write-Host " $LIN_SRV_IP is Ok"
}

#+END_SRC  

La tarea consiste en crearlo en una máquina en Windows 10. Para la creación del mismo
podeis utilizar el /Entorno Integrado de Desarrollo (IDE)/: =PowerShell ISE= y debéis 
crear el Script y ejecutarlo.

Una vez ejecutado y comprobado que funciona, realizad las siguientes modificaciones:

1. Cambiar la IP de =$LIN_SRV_IP= a 172.29.0.254. Comprobad que resultado da.
2. Cambiar la IP de =$LIN_SRV_IP= a vuestra máquina anfitriona. Comprobad el resultado.
3. Ampliar las comprobaciones de IP para que también compruebe:

   - 172.29.0.1
   - 172.29.0.254
   - Vuestra máquina anfitriona.

   Todas las comprobaciones han de ejecutarse en el mismo Script, añadiendo 
   lo que consideréis necesario para ello.

4. Añadir un mensaje de /error/ que aparezca cuando la conectividad no sea posible.
5. Mostrar en Verde cuando tengamos conectividad y en Rojo el mensaje de /error/.


Tras cada una de ellas, avisadme y le doy el visto bueno.

